from __future__ import annotations

from app.repositories.base import BaseRepository
from app.repositories.factory import (
    get_activity_match_repository,
    get_activity_repository,
    get_actual_progress_repository,
    get_audit_log_repository,
    get_conflict_repository,
    get_evidence_repository,
    get_extracted_progress_event_repository,
    get_field_report_repository,
    get_planner_review_repository,
    get_project_repository,
    get_schedule_repository,
    get_user_repository,
    get_wbs_repository,
    reset_all_repositories,
)
from app.repositories.in_memory import (
    InMemoryActivityMatchRepository,
    InMemoryActivityRepository,
    InMemoryActualProgressRepository,
    InMemoryAuditLogRepository,
    InMemoryConflictRepository,
    InMemoryEvidenceRepository,
    InMemoryExtractedProgressEventRepository,
    InMemoryFieldReportRepository,
    InMemoryPlannerReviewRepository,
    InMemoryProjectRepository,
    InMemoryScheduleRepository,
    InMemoryUserRepository,
    InMemoryWBSRepository,
)
from app.repositories.interfaces import (
    IActivityMatchRepository,
    IActivityRepository,
    IActualProgressRepository,
    IAuditLogRepository,
    IConflictRepository,
    IEvidenceRepository,
    IExtractedProgressEventRepository,
    IFieldReportRepository,
    IPlannerReviewRepository,
    IProjectRepository,
    IScheduleRepository,
    IUserRepository,
    IWBSRepository,
)

__all__ = [
    "BaseRepository",
    # Interfaces
    "IProjectRepository",
    "IScheduleRepository",
    "IWBSRepository",
    "IActivityRepository",
    "IFieldReportRepository",
    "IEvidenceRepository",
    "IExtractedProgressEventRepository",
    "IActivityMatchRepository",
    "IPlannerReviewRepository",
    "IConflictRepository",
    "IActualProgressRepository",
    "IAuditLogRepository",
    "IUserRepository",
    # In-memory implementations
    "InMemoryProjectRepository",
    "InMemoryScheduleRepository",
    "InMemoryWBSRepository",
    "InMemoryActivityRepository",
    "InMemoryFieldReportRepository",
    "InMemoryEvidenceRepository",
    "InMemoryExtractedProgressEventRepository",
    "InMemoryActivityMatchRepository",
    "InMemoryPlannerReviewRepository",
    "InMemoryConflictRepository",
    "InMemoryActualProgressRepository",
    "InMemoryAuditLogRepository",
    "InMemoryUserRepository",
    # Factory accessors
    "get_project_repository",
    "get_schedule_repository",
    "get_wbs_repository",
    "get_activity_repository",
    "get_field_report_repository",
    "get_evidence_repository",
    "get_extracted_progress_event_repository",
    "get_activity_match_repository",
    "get_planner_review_repository",
    "get_conflict_repository",
    "get_actual_progress_repository",
    "get_audit_log_repository",
    "get_user_repository",
    "reset_all_repositories",
]
